[package]
version = "0.1.0-alpha2"
description="Reactive Extensions for Rust"
license="MIT"
name = "rx"
repository="https://github.com/yingDev/rxrs"
authors = ["应元东 <ying@yingDev.com>"]

[dependencies]
