[package]
version = "0.1.0-alpha2"
description="Reactive Extensions for Rust"
license="MIT"
name = "rx"
repository="https://github.com/yingDev/rxrs"
authors = ["YingDev <me@yingDev.com>"]

[dependencies]
