[package]
name = "rsrs_workspace"
version = "0.1.0"
authors = ["应元东 <ying@yingDev.com>"]

[workspace]
members = ["rx", "example_gui", "rx_gtk"]

[dependencies]
rxrs = {path = "rx" }

[profile.release]
opt-level ='z'
lto = true