[package]
version = "0.1.0-alpha1"
description="Reactive Extensions for Rust"
license="MIT"
name = "rxrs"
repository="https://github.com/yingDev/rxrs"
authors = ["YingDev <ying@yingDev.com>"]

[dependencies]
